### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#1]
Da ich jetzt das AngularRouting für die einzelnen Seiten verwende, brauchen wir eine 404 Komponente oder zumindest einen Handler der wieder auf die Startseite verweist. Außerdem ist zu klären wie sich der Server bei einem Reload verhält. Eventuell muss da noch was konfiguriert werden.

**Comment by mimischi** [comment]
Was meinst du mit Reload? Was mit dem State passiert, wenn man die Seite im Browser neu lädt?

**Comment by mkay-sh** [comment]
Nee den clientseitigen State muss ich ja selber verwalten. Die Ionic Version nutzt im Moment kein Routing mit unterschiedlichen URLs. Beim Angular Routing ist das aber standartmäßig so und für Webapps auch empfohlen. Die Frage ist ob der Server für ein Request auf app.irgendwas.de/feedback (oder eine andere Unterseite) auch die SPA ausliefert oder einen 404 zurückgibt.

**Comment by mkay-sh** [comment]
Richtig, beide von dir beschriebene Szenarien sollten funktionieren. Frontendseitig braucht es dafür keine Anpassungen. Aber vermutlich muss der Server entsprechend mit einer SPA-Fallback Route ausgestattet werden.

**Comment by mkay-sh** [comment]
In netilify funktioniert das Szenario 2 schonmal nicht. Sobald wir die App mal im Staging laufen haben, müssen wir dort auch überprüfen wie es aussieht.

**Comment by mimischi** [comment]
Das Beispiel ist zwar für VueJS, ist aber Netlify spezifisch: https://cli.vuejs.org/guide/deployment.html#netlify

Ich kann das mal per PR etablieren.

**Comment by mimischi** [comment]
Hab gerade #11 erstellt. Szenario 2 funktioniert ohne Probleme.

**Comment by mkay-sh** [comment]
Damit ist dieses Problem gelöst.
