### ISSUE TITLE
Kristallsysteme

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#10]
Das Modul zeigt die in Processing erstellten 3D-Modelle.
Es gibt 7 Kristallsysteme, die anzuzeigen sind (und es werden nicht mehr weil Physik).

Je Kristallsystem müsste ein Satz von Buttons zur Verfügung stehen, mit denen Teile der Modelle ein-/ausgeblendet werden können (spezielle Ebenen, Koordinatensysteme...)

**Comment by sheepyhollow** [comment]
Die aktuellen Modelle sind in openprocessing gebaut. Eine Portierung in p5.js ist vermutlich ohne allzugroßen Aufwand möglich, falls das nötig oder einfacher wäre.

**Comment by sheepyhollow** [comment]
Aktuell können die Modelle nur die Millerschen Indizes anzeigen
(Mockup hier: https://user.uni-frankfurt.de/~bebuehne/geomat/crystalsystems/index2.html)
Erweiterungen wie Koordinatensysteme, Winkelbezeichnungen etc. müssten noch gebaut werden.

**Comment by mkay-sh** [comment]
Bis auf die Buttons sieht es schonmal ganz gut aus. Die weiteren Modelle fehlen noch.

**Comment by sheepyhollow** [comment]
Bis das GeoMat-Iconpack fertig ist können folgende Mat-Icons als Ersatz genommen werden:

Ersatzweise Mat-Icons für Crystalsystems
- Solid: checkbox_outline_black
- Axis: merge_type
- Points: apps

**Comment by mkay-sh** [comment]
Das eine Kristallsystem schon in den Preview rein.

**Comment by sheepyhollow** [comment]
Wie und wo (Platzaufteilung) könnte man noch einen Infotext einblenden?
Und wo speichern?

**Comment by sheepyhollow** [comment]
Der Infotext wird als JSON-Objekt in der <Model>.js gespeichert.

**Comment by sheepyhollow** [comment]
Camera Toggle funktioniert endlich. Easy, wenn man weiß, wie... 
Außerdem sind jetzt alle Modelle fertig gebaut. Ich bin aber noch nicht ganz zufrieden, da die Zentrierung noch nicht passt. Die Geometrie ist aus den alten _Processing_-Modellen konvertiert und das war dort ein bisschen lazy gelöst. Kann man aber immer noch nachbasteln, wenn Zeit ist.

**Comment by sheepyhollow** [comment]
Damit kann das Issue eigentlich geschlossen werden sobald der branch gemerged ist.

**Comment by sheepyhollow** [comment]
ah. _sobald_ er gemerged ist...
