### ISSUE TITLE
Bestimmungshelfer

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#15]
Ist in einer ersten Variante im dev Branch umgesetzt.

**Comment by mkay-sh** [comment]
- [ ] Navigation per Pfeiltaste
- [ ] Navigation per Swipe
- [ ] Stepper nicht notwendig

**Comment by sheepyhollow** [comment]
Alles drin - außer allgemeinen Styling-Sachen sehe ich keine Probleme.
Ich mache mir noch eine Notiz, dass wir nochmal nach den Inhalten schauen und z.B. auch bei "Tracht" ein Bild anzeigen.

**Comment by sheepyhollow** [comment]
Man kann im Bestimmungshelfer nicht scrollen (weder im Browser noch im mobilen Devmode-Preview)
