### ISSUE TITLE
Erläuterungstexte in der Steckbrief-Navigation

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#16]
In der Navigation des Steckbrief-Baums sollen (optionale) Kommentartexte zu den einzelnen Layern angezeigt werden. Damit können Schwerpunktsetzungen aus der Vorlesung und ggf. Abweichungen zur fachüblichen Systematik erläutert werden. 

Es muss noch geklärt werden, wo diese gespeichert sind (Frage auch an @chgad)
Zur UX haben wir noch keinen richtigen Plan.

**Comment by sheepyhollow** [comment]
also ähnliches Problem wie die Thumbnails...
Aber das können wir dann auch vielleicht gemeinsam lösen?

Ich muss Kerstin nochmal befragen, aber ich schätze, dass die zweite Variante sinnvoll ist mit Kommentar je Ebene.

Wäre es denn möglich eine unabhängige table mit Kommentaren (und thumbnails?) zu haben, die nach `split-systematic` (bzw. der kleinsten Einheit) geordnet ist. Und dass dann ein Abgleich passiert: Wenn es zur aktuellen split/sub einen passenden Eintrag gibt, dann füge ihn an, ansonsten nicht.
Das ist dann zwar ein hardcoding, aber es ist nur innerhalb einer Tabelle und wenn dort Informationen fehlen, gibt es eine generische Reaktion (z.B. ein generisches Thumbnail-Bild).

**Comment by sheepyhollow** [comment]
Nach Rücksprache mit Kerstin werden die Infotexte nach der ursprünglichen Idee nur für die Ebene der `sub_systematics` benötigt. Ich würde aber vorschlagen, dass wir allgemein bleiben und für jede Ebene die Möglichkeit vorsehen, einen Infotext einzublenden. Wenn keiner existiert, dann wird auch keiner angezeigt.

**Comment by sheepyhollow** [comment]
Frontend: Die Texte sollten nicht als default angezeigt werden, sondern z.B. mit einem Symbol ausgeklappt werden können (darin steht dann, warum der nächste Zweig nicht in der Datenbank vorhanden ist oder warum das Zeug nicht in der Vorlesung vorkommt etc. - de facto wird man das ein, zweimal lesen und hat es dann verstanden.)

**Comment by mkay-sh** [comment]
Ist umgesetzt. In der Staging Umgebung stehen nur noch keine Daten drinnen. #93
