### ISSUE TITLE
Feedback Basiskomponente

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#17]
Es soll ein Feedbackformular zur Verfügung stehen, mit dem Rückmeldungen, Bug-Reports etc. gesendet werden können. 

Platzierung im Menü und, wenn das nach wie vor alle als sinnvoll erachten, als Balken in der Startansicht. Wenn wir eine gute Idee haben, das in jedem View/State unterzubringen, dann wäre das auch denkbar. Ziel ist, die Hürde für Feedback so niedrig wie möglich zu halten.

Das Formular versendet aktuell an eine Mailadresse; das kann auch b.a.w. so bestehen bleiben.

**Comment by mkay-sh** [comment]
Ich würde es auf jeden Fall mit ins Menü packen. Ein Balken auf der Startseite ist auch kein Problem. Wäre halt die Frage, ob man den in jedem View haben möchte. 
Zusätzlich zu dem Feedbackformular soll es mit #14 Sentry die Möglichkeit geben bei Fehlern einen BugReport zu schreiben.

**Comment by mkay-sh** [comment]
Name: nicht required
Email: required
Art der Nachricht: Default Feedback
Anmerkungen: Höheres Feld

**Comment by sheepyhollow** [comment]
Sieht prima aus! Die Option "etwas anderes" kann noch raus, ansonsten passt das so.
Da das Feedback jetzt im Menü ist, kommt man auch von überall dran.Man könnte die Hürde noch durch ein Feedback-Icon

**Comment by mkay-sh** [comment]
In #20 umgesetzt.
