### ISSUE TITLE
Steckbrief Basiskomponente

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#2]
Das Modul stellt den Strukturbaum der einzelnen Minerale ('mineraltype') und die Mineralsteckbriefe dar.
Der Strukturbaum soll dynamisch und iterativ aus der Abfrage `/profiles/{layer}/{item}` generiert werden.

- [x] Baumanzeige der Einträge 
- [x] Steckbrief neben dem Baum (große Bildschirme) 
- [x] Steckbrief einzeln anzeigen (kleine Bildschirme)
- [ ] ~~Namen des Eintrags mit Pfad durch Kategorien darstellen~~
Wird nicht gemacht, da auf kleinen Bildschirmen nicht genug platz dafür ist und wir auf großen Bildschirmen eh den Baum sehen.
- [ ] ~~Thumbnails für Kategorien (Blocker: https://github.com/GeoMatDigital/django-geomat/issues/296)~~ Braucht es in der Baumansicht nicht mehr
- [x] In einer Kategorie durch Swipe/Button hin und her navigieren
- [x] Toolbar nur über den Steckbrief.
- [x] Ganzen Ast anklickbar (nicht nur Icon)
- [x] Äste automatisch wieder einklappen
- [x] Seperates Scrolling Baum/Steckbrief

**Comment by sheepyhollow** [comment]
Wir müssen noch festlegen, wie (= an welcher Stelle) die Anzeige des Eintrags erfolgt. In der Ionic App stand diese im Header der Seite ganz oben.
Nach unserer letzten Besprechung halten wir es für sinnvoller, wenn oben die Komponente steht ("Steckbriefe") und der Name des aktuellen Minerals an oberster Stelle im Steckbrief als Titel. Danach folgt das Bild und darunter wird ggf. ein alternativer Name angezeigt.
In der Datenbank sind bis zu drei Namen gespeichert: Trivialname, Mineralname und Varietät.

Diese sollen nach folgenden Regeln angezeigt werden:

- Wenn Varietät vorhanden, dann Varietät in den Titel und Mineralname unter dem Bild anzeigen. 
- Wenn Varietät nicht vorhanden, dann den Mineralname in den Titel.
- Wenn ein Trivialname vorhanden ist bzw. falls Trivialname anders als Mineralname: Mineralname in den Titel und Trivialname unter dem Foto einblenden.   

Pseudocode

```
if (variety) {title = variety; display minerals below img}
else (title = minerals)

if (trivial_name || (minerals != trivial_name)) {display trivial_name below img}
```

Heißt auch: der Trivialname wird nie als Titel angezeigt!

**Comment by sheepyhollow** [comment]
Das Item "Bild" braucht keine Überschrift. An dieser Stelle soll der Titel stehen.

**Comment by sheepyhollow** [comment]
Demnächst wird einem Steckbrief noch "approximierte Farbe" und "approximierte Strichfarbe" hinzugefügt.
https://github.com/GeoMatDigital/django-geomat/issues/281
https://github.com/GeoMatDigital/django-geomat/issues/278

 Wir haben noch nicht abschließend entschieden, ob und wie wir diese im Steckbrief anzeigen. Aber das würde bedeuten, nur ein Feld mit Farbcode hinzuzufügen.

**Comment by sheepyhollow** [comment]
Die Formatierung der Chemischen Formel müsste sich aus der alten App ergeben.

**Comment by sheepyhollow** [comment]
Wenn wir die Anzeige des Namens so machen, wie oben beschrieben, dann ist die Information über den Baum im eigentlichen Steckbrief nicht mehr sichtbar; d.h. man sieht nicht mehr, wo im Baum man sich befindet. Daher müsste es ein Feld geben, in dem `systematics` | `split_systematics` | `sub_systematics` angezeigt werden, z.b. in einer Zeile mit Trennzeichen (so eine Art von breadcrumbs).
Oder gibt es hierzu noch bessre UI Ideen?

**Comment by mkay-sh** [comment]
Entweder so, oder wir zeigen den eigentlichen Steckbrief auch als overlay an.

**Comment by mkay-sh** [comment]
Die Komponente ist soweit umgesetzt. Der Teil mit der Galerie gehört ja in #3 .

**Comment by sheepyhollow** [comment]
Steckbriefe und Baum sollten sich separat scrollen lassen. 
Wenn der Baum weit ausgeklappt ist, dann muss man zum Steckbrief immer nach oben scrollen.
Evtl. könnte man (zusätzlich) auch Äste wieder automatisch einklappen.

**Comment by sheepyhollow** [comment]
Ich würde vorschlagen, den gesamten Text eines Astes klickable/tappable zu machen und nicht nur den Pfeil.

**Comment by mkay-sh** [comment]
Cursor anpassen beim Baum

**Comment by sheepyhollow** [comment]
Im Baum müssten noch die richtigen Namen stehen, konform zu hier: https://github.com/GeoMatDigital/web-geomat/issues/2#issuecomment-457933796

Das, was auch im `Titel` steht, sollte im Baum stehen.

**Comment by sheepyhollow** [comment]
Bei einer Breite < 800px im Devmode-Preview werden die einzelnen Steckbriefe nicht angezeigt (Chrome & FF unter Windows).

**Comment by sheepyhollow** [comment]
Die Kommentare (`other`) werden in der Steckbrief-Detailansicht offenbar nicht angezeigt.

**Comment by sheepyhollow** [comment]
Scroll by touch der Steckbrief-Detailansicht funktioniert auf (meinem) Tablet nicht.
Im Baum allerdings schon.

**Comment by mkay-sh** [comment]
So Name ist sowohl im Header als auch im Baum angepasst.
Der Fehler das die Steckbriefe nicht angezeigt werden ist auch behoben.

**Comment by mkay-sh** [comment]
Das scroll by touch kann ich leider nicht reproduzieren. Magst du nochmal schauen ob der Fehler immer noch besteht oder nicht?

**Comment by sheepyhollow** [comment]
Ich schlage wie abgesprochen vor, dieses Issue nun zu schließen und die noch offenen Punkte (Scroll by touch/sonstige Darstellungsfehler, Kommentare, Farben) in eigenen Issues zu verhandeln.
