### ISSUE TITLE
Audio und Begleittexte

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#22]
In der Galerie-Hauptansicht soll die Möglichkeit bestehen, einen Audiostream mit einem Beschreibungstext abzuspielen. Ebenso sollte der Text auch lesbar angezeigt werden.

**Comment by mkay-sh** [comment]
Play, Pause, Restart Button in die Toolbar und einen InfoTab mit dem Text. Erstmal noch keinen ProgressBar mit der aktuellen Wiedergabeposition.

**Comment by sheepyhollow** [comment]
Die Audiostreams stoppen nicht beim Wechseln des Minerals (ich kann mehrere parallel starten).
Außerdem werden, wenn ein Stream pausiert, die Zeiten auch bei anderen Mineralen angezeigt.
Hierfür müssen wir noch das optimale Verhalten definieren.

**Comment by mkay-sh** [comment]
Ich würde vorschlagen beim Wechsel des Minerals stoppt der Audiostream einfach. Alles andere wäre seltsam darzustellen.

**Comment by sheepyhollow** [comment]
Innerhalb eines Minerals sollte der Stream allerdings weiterlaufen.

**Comment by mkay-sh** [comment]
Wenn ich das richtig sehe, ist soweit alles umgesetzt? Falls noch neue Fehler auftreten gerne in einem neuen Issue.
