### ISSUE TITLE
Bildergröße

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#226]
Gallerie Scrolling
Bildergröße nicht größer als 100%
Swipe geht nicht in Chrome

**Comment by sheepyhollow** [comment]
Bildergröße ist nun richtig - zumindest im Prinzip. Es müsste noch Window-Resize abgefangen werden (da werden die Bilder aktuell gestaucht).

Dabei festgestellt: unter FF werden im maximierten Fenster (Win10) die Menü und Glossar eingeklappt angezeigt, auch bei `width > 1280`. Im Nicht-Vollbild funktioniert es.
Chrome zeigt in beiden Fällen oberhalb der Schwelle die Menüs an (wie erwünscht).

**Comment by mkay-sh** [comment]
So bitte erneut überprüfen...
