### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#227]
Es soll die Möglichkeit geben, Messages anzuzeigen, um die Benutzer über Updates oder sonstige Dinge zu informieren (z.B. auch Adventskalender).

Eine Message muss folgende Felder vorsehen haben (Vorschlag):

```typescript
interface Message {
  title: string; // message subject
  text: string; // Markdown content
  startdate: DateTime; // message should be visibile from
  enddate: DateTime; // message should be visibile until
}
```

**Comment by sheepyhollow** [comment]
Die Messages müssen im Backend realisiert werden.

**Comment by sheepyhollow** [comment]
Brauchen wir zusätzlich ein `dimiss`-Szenario? Und muss das in der Datenstruktur repräsentiert werden?
Oder wird es eher sowas wie eine ID-Liste in einer Liste im local user.
Die Messages sollten auf der Landingpage angezeigt werden und dann in einer Unterseite aufgelistet werden.

**Comment by mkay-sh** [comment]
Wenn wir auch den Changelog darüber realisieren wollen wäre noch ein type sinvoll. Dann kann man das leichter trennen.
```typescript
interface Message {
  title: string; // message subject
  text: string; // Markdown content
  startdate: DateTime; // message should be visibile from
  enddate: DateTime; // message should be visibile until
  type: 'message' | 'changelog' | ... ;
}
```

**Comment by mkay-sh** [comment]
Jo das können wir gerne so machen. Ist aber ja frontendseitig umzusetzen. Da wir keine User haben ist ein Dismiss oder ähnlich einfach nur im LocalStorage zu speichern. Ich würde auf der Startseite keine Tabs machen sondern die Unterseite im Menü vorziehen. Damit die Startseite möglichst "clean" ist.

**Comment by mkay-sh** [comment]
Valid From im Titel anzeigen...

**Comment by sheepyhollow** [comment]
...und noch ein bisschen Padding zwischen der `h3`-Überschrift und der `mat-line`. Ich krieg's irgendwie nicht selbst hin.

**Comment by sheepyhollow** [comment]
Ah, doch. Aber nicht sicher, ob man das so macht.

**Comment by sheepyhollow** [comment]
Die Formatierung des `validFrom`-Datums überlasse ich Dir... @mkay-sh 😬

**Comment by sheepyhollow** [comment]
Ich würde vorschlagen, dieses Issue mit dem `1.1.0`-Release zu schließen und das Thema Changelog-Anzeige in #228 weiter zu verhandeln.
