### ISSUE TITLE
Systematik anzeigen

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#230]
Wenn ich ein Bild der Galerie öffne und dort in den Steckbrief gehe, sehe ich nicht, an welcher Stelle der Systematik das zugehörige Mineral eingeordnet ist. Diese Information müsste aber da stehen.

**Comment by mkay-sh** [comment]
Was genau ist damit gemeit? Der Pfad innerhalb des Steckbriefbaums? Oder nur die Obergruppe?

**Comment by sheepyhollow** [comment]
Kläre ich morgen nochmal mit Kerstin. Beim gesamten Pfad wird das 'ne lange Zeile. Aber eigentlich wäre es am richtigsten so.

**Comment by sheepyhollow** [comment]
Nur den nächsthöheren Eintrag anzeigen, müsste `systematics` sein (keine nodes)

**Comment by mkay-sh** [comment]
Ok. `systematics` haben wir nicht mehr, da wir inzwischen ja ein Tree Konzept in der Datenbank haben. Was soll der User mit diesem Eintrag anfangen können? Muss da auch eine Navigation in den Steckbriefbaum gehen?

**Comment by sheepyhollow** [comment]
in `handpiece` wird aber `systematics` ausgegeben. Entspricht das nicht den `Leaf_nodes`? 
![image](https://user-images.githubusercontent.com/13869236/65053704-a6399e00-d96c-11e9-9933-4f4bb735cec7.png)

**Comment by sheepyhollow** [comment]
> Muss da auch eine Navigation in den Steckbriefbaum gehen?
Nicht zwingend. Aber wenn ich die Galerie von den (isolierten) Handstücken aus betrachte, dann sollte ich als User auch sehen können, wohin die gehören. Eine Navigation in den Steckbrief halte ich nicht für nötig - dann müssten wir unsere "crosslink"-Strategie ja nochmal überdenken und dann wären auch das Steckbriefe-Tab obsolet.

**Comment by mkay-sh** [comment]
Ist ja bereits umgesetzt, entspricht das den Anforderungen so?

**Comment by sheepyhollow** [comment]
Kerstin sagt: ja!

**Comment by sheepyhollow** [comment]
Sorry, aber wir haben uns das nochmal angesehen und im Steckbrief sieht man die Systematik ja nur, wenn man richtig über den Baum geht. Wenn man die Suche verwendet oder den Baum gerade nicht sieht (weil Handy), dann sieht man die Systematik nicht.

Heißt also: Systematik auch im Steckbrief anzeigen und damit sind die Steckbriefe identisch (egal ob in Galerie oder Steckbrief direkt)

**Comment by sheepyhollow** [comment]
Ich meine, der o.g. commit sei bereits im `master`, ich sehe jedoch die Systematik nicht im Steckbrief.
