### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#233]
Auf einem englisch eingestellten OS werden die DB-Einträge im Steckbrief auf Englisch angezeigt (und z.T. komisch übersetzt). Das Thema hatten wir schonmal, gibt es da einen Workaround?

**Comment by sheepyhollow** [comment]
Vermutlich gehört das aber ins Backend.

**Comment by mkay-sh** [comment]
Ich hab da nochmal was angepasst. Eventuell geht es dann. Wenn nicht muss das Backend anders vorgehen....

**Comment by mkay-sh** [comment]
@sheepyhollow Magst du nochmal checken ob das auf geomat.netlify.com jetzt immernoch auftritt?

**Comment by mkay-sh** [comment]
Erstmal geschlossen. Man sollte sich überlegen ob das i18n Modul im Backend nicht eh deaktiviert werden kann.
