### ISSUE TITLE
Kristallsysteme Infotext

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#234]
Der Infotext liegt bereit und kann angezeigt bzw. in die Oberfläche integriert werden.
Wie das aussehen kann, wird noch abgesprochen.

**Comment by mkay-sh** [comment]
Erste Version mit Overlay im entsprechenden Branch drinnen. Wie genau das aussehen kann ist ja flexibel.

**Comment by sheepyhollow** [comment]
Idee von uns: togglebar über den Button, aber nicht als popup/modal, sondern am unteren Bildrand wie eine Snackbar, so dass man das Modell noch bedienen kann.

**Comment by sheepyhollow** [comment]
...wobei Snackbars ja auch verschwinden, wenn man etwas anderes im Fenster tut.
Das würde alles außerhalb des iframes passieren, richtig? Also ein Balken am unteren Rand wäre ideal, das kann ja auch außerhalb des iframes sein.
