### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#24]
Eine globale Suchfunktion wurde bereits diskutiert und als zu aufwändig verworfen.
Eine Suche nach Mineralnamen wäre in Steckbrief- und Galerieübersicht jedoch interessant.

**Comment by mkay-sh** [comment]
Für den Baum wäre das eher eine Filterfunktion.

**Comment by sheepyhollow** [comment]
Wir müssen dozentenseitig klären, welche Arten von Filterung und Suche sinnvoll sind

**Comment by sheepyhollow** [comment]
In Galerie UND Steckbrief sollte nach folgenden Einträgen gesucht werden können:
- Mineralname (`minerals`)
- Varietät (`variety`)
- Trivialname (`trivial_name`)
Nach Bildnamen (`name`, z.B. Klinochlor auf Quarz) muss in der Galerie nicht gesucht werden können.

Kann das realisiert werden?
Wie würden die Ergebnisse angezeigt werden? 
Wie geht es danach weiter?

**Comment by sheepyhollow** [comment]
Steckbrief: Ergebnisse als Liste anzeigen
Galerie: nur Bilder anzeigen, auf die der Suchfilter passt.

**Comment by sheepyhollow** [comment]
Steckbrief: Ergebnisliste anzeigen 
Galerie: nur die zum Suchfilter passenden Bilder anzeigen

**Comment by mkay-sh** [comment]
In der Gallerie umgesetzt.

**Comment by sheepyhollow** [comment]
Whoa, sehr edel! Kann das Suchfeld noch in den focus? Ich muss im Moment extra klicken/tippen damit der Cursor erscheint.

**Comment by sheepyhollow** [comment]
Supi - aber kann der Text noch in der Card zentriert werden (horizontal und vertikal) und wie im letzten Kommentar ausführlicher formuliert sein?

**Comment by sheepyhollow** [comment]
Oh - und im Steckbrief ist die Suche auch, sehr fein! Ich spreche nochmal mit Kerstin, ob sie - wie aktuell - immer da sein soll. Aber eigentlich finde ich das so sinnvoll. Da die Steckbriefe keine eigene Leiste haben (wie die Galerie) ist das eigentlich der richtige Ansatz.

**Comment by sheepyhollow** [comment]
Übrigens gibt es für die Suche auch ein eigenes Icon.

**Comment by sheepyhollow** [comment]
...das auch neben dem Suchfeld in den Steckbriefen erscheinen sollte.
