### ISSUE TITLE
Menüreihenfolge

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#247]
Die Abfolge der Module im Hamburgermenü sollte konsistent zu den Schnellzugriffen der Landingpage sein. Folgende Reihung schlagen wir vor:

- Steckbriefe 
- Galerie
- Bestimmungshelfer
- Kristallsysteme
- Selbsttest
- Info (bisschen langweilig, aber ein anderes Tool haben wir da nicht)

**Comment by mkay-sh** [comment]
Neue Reihenfolge wie oben mit folgenden Ergänzungen:

- Startseite
- ... wie Oben
- Datenschutzerklärung
- Feedback

**Comment by sheepyhollow** [comment]
Die Steckbriefe erscheinen doppelt im Menü, außerdem stimmt die Reihenfolge nicht ganz - das kann aber aus dem letzten Merge stammen.

**Comment by mkay-sh** [comment]
Jo, das war ein Fehler aus dem merge....
