### ISSUE TITLE
Versionierung

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#249]
Vermutlich völlig unwichtig... 😃  aber wollen wir für unsere Releases irgendein Versionierungsschema einführen? Bislang firmiert die (alte) App unter 0.2.0. Ich denke, dass wir mit dem WS-Release fairerweise eine 1._ davorschreiben können.

**Comment by mkay-sh** [comment]
Versionsschema ist schon sinnvoll ;) 1.x.x für das Release zum WiSe klingt gut. Anschließend würde ich bei neuen Features Minor Releases erzeugen und für Bugfixes natürlich Patch Releases.
Nächstes Major Release wäre für mich der Umstieg wenn wir den Biokram auch können wollen.

**Comment by sheepyhollow** [comment]
make ist so. Close? Oder als Reminder behalten?
