### ISSUE TITLE
Sortierfunktion

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#25]
In der Galerieübersicht wird aktuell eine feste Reihenfolge (nach der Vorlesung) vorgegeben.
Es könnte aber auch eine Sortierfunktion geben, mit der nach Alphabet oder ggf. auch nach Systematik sortiert werden kann (oder nach Chemismus... etc. etc.).
Was davon könnte mit vertretbarem Aufwand umgesetzt werden?

Siehe dazu auch #24 (Suchfunktion)

**Comment by mkay-sh** [comment]
Eine Sortierfunktion in Steckbrief oder der Galerie erscheinen uns nicht sinnvoll.

**Comment by sheepyhollow** [comment]
Schön, dass wir es trotzdem zum Teil gemacht haben :)
