### ISSUE TITLE
Link auf das Repository

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#258]
Sollen wir auf der Infoseite sowohl Frontend als auch Backend Repository verlinken? Oder einfach die ganze Github Organisation?

**Comment by sheepyhollow** [comment]
Eigentlich die Organisation - allerdings könnten wir mal überlegen, wie wir app-geomat loswerden, archivieren oder inaktiv schalten o.ä. Weiß nicht, was GitHub da ermöglicht.

**Comment by mkay-sh** [comment]
Archivieren ist möglich. Also einen Link auf die ORG einfach in der Infoseite?

**Comment by sheepyhollow** [comment]
Jawohl, Infoseite ist gut. Ich würde das vor Semesterrelease eh nochmal drübergehen und etwas mehr Text schreiben (können wir da eigentlich direkt eine .md-Datei einbinden? Oder muss das HTML sein?)

Mit dem Archivieren warten wir noch einen Moment bis wir die alte App ganz gekillt haben. Im Prinzip sobald #5 erledigt ist (bzw. wir im Quiz effektiv mehr zu bieten haben als der Status Quo)
