### ISSUE TITLE
Quiz Auswertung

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#289]
Fragenauswertung:

* Zu _allen_ Antworten richtig/falsch anzeigen (Farbe bzw. Symbol)
* Feedback nur zu den ausgewählten Antworten anzeigen

Dies entspricht dem Verhalten der alten App. Wir haben uns nochmal beraten und finden das so gut. Ist es bei Single Choice auch ohne Weiteres möglich, die nicht-gewählten Antworten "aufzulösen" bzw. farblich/symbolisch (X) hervorzuheben?

**Comment by mkay-sh** [comment]
SingleChoice umgesetzt. MultipleChoice fehlt noch die Auswertung für Menschen mit eingeschränkter Farbwahrnehmung.

**Comment by sheepyhollow** [comment]
Insgesamt sieht das gut aus, was ich sehe - aber im `quiz.service.ts` werden aktuell die Single Choice-Fragen herausgefiltert. 

Und vielleicht passen wir demnächst nochmal die Farben an - das rot `mat-color($warn)` ist ein bisschen sehr prominent - und warum eigentlich blau für richtig? Üblich, wenn auch nicht barrierefrei, wäre ja eher grün. Ich bespreche das aber nochmal mit Kerstin.

**Comment by mkay-sh** [comment]
Blau hatte ich nur verwendet weil es die akzentfarbe ist. Ziel war es nicht so viele verschiedene Farben in die App zu hauen, damit es übersichtlicht bleibt. Kann auch gerne auf ein grün wechseln und nicht so prominente Farben nehmen. 
Der andere Fehler ist ein Debug Artifakt... entferne ich.

**Comment by mkay-sh** [comment]
Blau hatte ich nur verwendet weil es die akzentfarbe ist. Ziel war es nicht so viele verschiedene Farben in die App zu hauen, damit es übersichtlicht bleibt. Kann auch gerne auf ein grün wechseln und nicht so prominente Farben nehmen. 
Der andere Fehler ist ein Debug Artifakt... entferne ich.

**Comment by sheepyhollow** [comment]
Ich habe im nächsten Hotfix-Commit die Darstellung der MC-Auswertung in Absprache mit Kerstin nochmal angepasst. Falsche Antworten werden jetzt alle mit `indetermined` angezeigt, richtige Anworten mit `checked`.

Wenn ich einen Tipp kriege, wie man das mit der Farbdefinition im Theme korrekt macht, dann kann ich das auch selbst einbauen.

**Comment by mkay-sh** [comment]
Sind wir hiermit durch?

**Comment by sheepyhollow** [comment]
Ja, schließen wir das - ist noch nicht perfekt (barrierefrei), aber das ist ne eigene Baustelle.
