### ISSUE TITLE
Quiz-Texte

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#290]
Texte im Sinne von https://github.com/GeoMatDigital/web-geomat/issues/5#issuecomment-532378672 anlegen.

**Comment by mkay-sh** [comment]
Die Texte kannst du in der Datei `src/app/modules/quiz/components/quiz-end/quiz-end-feedback.ts` eintragen.

**Comment by sheepyhollow** [comment]
Ich war so frei, das doch etwas aufzubohren. Das Ergebnis (n von m Fragen) sollte jedes Mal angezeigt werden und steht nun in der `quiz-end.component.-html` drin. Dafür wird die Percentage im Feedback ausgegeben.

**Comment by mkay-sh** [comment]
Sieht super aus ;)
