### ISSUE TITLE
Sentry & GDPR

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#299]
Sentry muss ggf. in der Datenschutzerklärung berücksichtigt werden; evtl. benötigen wir sogar einen Auftragsverarbeitungs-Vertrag (den Sentry auch automatisiert anbietet).

ggf. ist das hier hilfreich: https://blog.sentry.io/2018/03/14/gdpr-sentry-and-you

**Comment by sheepyhollow** [comment]
https://www.bitfactory.io/de/blog/app-entwicklung-und-datenschutz-grundverordnung/

**Comment by mkay-sh** [comment]
Unsere Sentryeinstellungen verhindern schon das Speichern von IP Adressen. Ich bin mir nicht sicher ob wir die Auftragsverarbeitung brauchen, weil wir das ganze ja selbst hosten. Opt-Out muss manuell umgesetzt werden.

**Comment by mimischi** [comment]
Ich weiß nicht, ob für Sentry ein Opt-Out notwendig ist. Habe mir für eine andere Seite über e-recht24.de einfach folgendes für die Datenschutzerklärung generiert:

> ## Sentry Stabilitätsüberwachung und -prüfung
> Wir verwenden den Dienst Sentry (Sentry, 1501 Mariposa St #408, San Francisco, CA 94107, USA), um die technische Stabilität unseres Dienstes durch Überwachung der Systemstabilität und Ermittlung von Codefehlern zu verbessern. Sentry dient alleine diesen Zielen und wertet keine Daten zu Werbezwecken aus. Die Daten der Nutzer, wie z.B. Angaben zum Gerät oder Fehlerzeitpunkt werden anonym erhoben und nicht personenbezogen genutzt sowie anschließend gelöscht. Für weitere Informationen verweisen wir auf die Datenschutzerklärung von Sentry: https://getsentry.com/privacy/

**Comment by mkay-sh** [comment]
@sheepyhollow trägst du das in die Datenschutzseite ein? Du wolltest da doch noch irgendwas anderes daran ändern.

**Comment by sheepyhollow** [comment]
Is schon drin, sonst hätte ich das oben nicht abgehakt.

**Comment by sheepyhollow** [comment]
> Ich bin mir nicht sicher ob wir die Auftragsverarbeitung brauchen, weil wir das ganze ja selbst hosten.

Stimmt. Das passt dann so.
