### ISSUE TITLE
Crosslink Galerie/Steckbrief

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#3]
Es soll eine Möglichkeit geben, vom Steckbrief in die Galerie zu springen bzw. umgekehrt. 
Bislang besteht die Idee, dazu ein Icon zu verwenden, das im Bild angezeigt wird.

**Comment by sheepyhollow** [comment]
Galerie bezieht sich hier vor allem auf die Ansichtstools (i.e. Zoom) - das Bild selbst ist ja im Steckbrief auch sichtbar.

**Comment by mkay-sh** [comment]
Es soll also nur das bildschirmfüllende Modal, in dem das große Bild angezeigt wird.
Das Modal kann bisher ja noch nicht so viel, außer der Darstellung. Kommen da eventuell noch mehr Bilder oder soll es noch sowas wie einen Zoom etc. geben?

**Comment by sheepyhollow** [comment]
Der Plan für die Galerie (steht demnächst im entsprechenden issue), dass man nicht nur ein Modal mit Bild hat, sondern eben auch ein paar Tools, von denen der Zoom das wichtigste ist. Das ist in der bisherigen Version noch nicht implementiert.

**Comment by mkay-sh** [comment]
- [ ] Buttons zur Navigation, BrowserBack/Forward funktioniert durch das URL Routing automatisch
- [ ] Es werden jeweils die zugehörigen Dinge angezeigt.

**Comment by mkay-sh** [comment]
Nach der Besprechung mit Kerstin folgender Plan für den Crosslink:
1. Galerie
  Die Thumbnails öffnen sich nicht mehr in einem Overlay, sondern in einer eigenen Komponente. In dieser gibt es 2 Tabs. Im ersten ist das Bild mit den Tools (Zoom, Maßstab, etc.) Im Zweiten wird der Steckbrief angezeigt.

2. Steckbriefe
   Wenn man im Steckbrief auf das Bild klickt öffnet sich der gleiche Inhalt wie für den ersten Tab in der Galerie.

**Comment by sheepyhollow** [comment]
Tatsächlich ergibt sich hier noch ein Spezialfall: im Steckbrief-Tab der Galerieansicht muss der **Mineralname** noch als Feld hinzugefügt werden, da im Header der Name des Handstücks angezeigt wird. D.h. die Galerie (und ihr Steckbrief) basiert auf dem Handstück; die Steckbriefe im Baum auf den Mineralarten.

**Comment by mkay-sh** [comment]
So den Spezialfall können wir jetzt auch ;)
Schau es dir doch gerne mal an und wenn es passt mach den Issue gerne zu.

**Comment by sheepyhollow** [comment]
Ich muss hier doch nochmal nachhaken - ggf. wird das auch ein eigenes Issue.
Aus der Galerie kommend habe ich Zugriff auf Bild, Steckbrief, Beschreibungstext (+ ggf Audio). 
Was ist aber, wenn ich im Steckbrief bin? Komme ich von dort direkt in die Galerie?

**Comment by mkay-sh** [comment]
Bisher haben wir das nicht vorgesehen. Wenn wir das haben wollen gerne in einem neuen Issue.
