### ISSUE TITLE
Browsercheck

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#316]
Warnung einbauen wenn ein browser veraltet ist, da dann nicht alle Funktionen verfügbar sind.
Vorallem läuft das ganze im IE garnicht, weil der verschiedene von uns verwendete APIs nicht unterstützt.

**Comment by mimischi** [comment]
Gibt es keine Möglichkeit das mit Polyfills zu lösen? Ich dachte man kann alle möglichen APIs damit nachliefern. Allerdings wird eben das Bundle dadurch riesig.

**Comment by mkay-sh** [comment]
Kann man machen. Aber manche Sachen lassen sich nicht gut Polyfillen. Zum Beispiel setzen wir sehr intensiv das CSS Grid ein, und dafür gibt es keinen gescheiten Polyfill.

**Comment by mkay-sh** [comment]
In einer ersten Version umgesetzt. @sheepyhollow kann noch den Text anpassen wenn er möchte.
