### ISSUE TITLE
Slideshow Images

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#328]
Wir brauchen die Möglichkeit in Slideshows Bilder schick anzuzeigen ;)

**Comment by sheepyhollow** [comment]
Vorschlag: Bilder in der `pages.ts` auflisten und mit material stylen. Es ist keine große Einschränkung, wenn die Bilder nur unterhalb des Textes angezeigt werden. Aber je nach Breite zweispaltig klnnte gut aussehen. Text lieber einspaltig (wegen der Aufzählungen)

**Comment by mkay-sh** [comment]
Ist in einer ersten Version umgesetzt. Magst du die Bilder noch entsprechend eintragen @sheepyhollow ? Ich hab auch direkt die Anpassungen gemacht, die später nötig werden wenn wir mehrere Slideshows haben und die Slideshows in den State gepackt.

**Comment by sheepyhollow** [comment]
Aktuell tritt beim Navigieren mit der Tastatur oder per Swipe ein Fehler auf.

**Comment by sheepyhollow** [comment]
Außerdem erscheint die Seite bzw. das Bild beim ersten Laden für ganz kurze Zeit doppelt. Ist aber vllt. nur ein Darstellungsding.

**Comment by mkay-sh** [comment]
Was noch fehlt:
- [ ] Tastatur/Swipenavigation
- [ ] Bilder alle möglichst gleich groß
- [ ] Doppelte Darstellung beim ersten Laden

**Comment by mkay-sh** [comment]
Die Doppelte Darstellung kann ich nicht mehr reproduzieren. Falls sie nochmal auftaucht das Issue einfach wieder öffnen.
