### ISSUE TITLE
Rücksprungpunkt Galerie (UX)

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#366]
Beim Verlassen der Galerie (Back-Button oder Pfeil-nach-oben) sollte man wieder an der Stelle der Galerie ankommen, an der man das Bild geöffnet hat und nicht am Anfang der Galerie.

**Comment by sheepyhollow** [comment]
Wird mit dem Umbau möglicherweise sowieso anders.

Allerdings wird die Galerie ja auch jedes Mal neu aufgebaut (man sieht die loader, wenn auch nur kurz). Keine Ahnung, ob man das ohne Overlay überhaupt anders lösen kann.

**Comment by mkay-sh** [comment]
Brauchen wir nach dem Umbau nicht mehr, da die Gallerieansicht wegfällt. #393
