### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by mkay-sh** [GeoMatDigital/web-geomat#39]
Markdown Support für die Texte innerhalb der App.
Mögliche Syntax wird:
`~` Tiefstellung
`^` Hochstellung
`_` Kursiv
`**` Fett

Unicode Sonderzeichen werden unterstützt.
Da das Markdown zu HTML compiliert wird, können die bestehenden Tags so bleiben und wir nutzen die Syntax einfach nur in neuen Texten.

**Comment by sheepyhollow** [comment]
Wie werden Absätze dargestellt? Es sollte einen kleinen Abstand geben; keine ganze Leerzeile.

**Comment by mkay-sh** [comment]
In Markdown wird Text in Paragraphen dargestellt. Wenn man einen Zeilenumbruch macht, landet der Text in einem Paragraphen. Also gibt es keinen Abstand. Wenn man zwei Zeilenumbrüche macht, landet der Text in einem neuen Paragraphen und es gibt Abstand dazwischen. Den Abstand können wir per CSS auch verkleinern, so dass es nicht wie eine ganze Freizeile aussieht.

**Comment by sheepyhollow** [comment]
>Den Abstand können wir per CSS auch verkleinern, so dass es nicht wie eine ganze Freizeile aussieht.
make it so

**Comment by mkay-sh** [comment]
<img width="714" alt="Screenshot 2019-09-09 at 21 01 46" src="https://user-images.githubusercontent.com/24921097/64558857-306a7c80-d345-11e9-8db3-e3487d1e2f9b.png">
Like this?

**Comment by sheepyhollow** [comment]
MD sieht jetzt gut aus.

**Comment by sheepyhollow** [comment]
Für die Blickrichtungen (vgl. #235) wird in der Kristallographie eine Notation mit einem Strich über einer Zahl verwendet (overline). Lässt sich das in Kombination mit MD umsetzen?

`1<SPAN STYLE="text-decoration:overline">1</SPAN>1` wird ignoriert.

Betrifft Bestimmungshelfer, Steckbriefe (strings in `cleavage.coordinates`) und Kristallsysteme

**Comment by mkay-sh** [comment]
> Für die Blickrichtungen/Millersche Indizes (vgl. #235) wird in der Kristallographie eine Notation mit einem Strich über einer Zahl verwendet (overline). Lässt sich das in Kombination mit MD umsetzen?
> 
> `<SPAN STYLE="text-decoration:overline">1</SPAN>` wird ignoriert.
> 
> Betrifft Bestimmungshelfer, Steckbriefe (strings in `cleavage.coordinates`) und Kristallsysteme

Entweder kann der obige HTML String so mit in den Markdowntext. Das würde funktionieren. Wenn es oft genug verwendet wird, können wir dafür auch ein Zeichen ähnlich dem Supscript einbauen. Da bräuchte ich einen Vorschlag von eurer Seite aus.

**Comment by sheepyhollow** [comment]
Ich habe den HTML-String mal in einem Beschreibungstext (Epidot) eingesetzt, die Anweisung wird aber dort ignoriert.

**Comment by mkay-sh** [comment]
Problem gefunden. Der Angular DomSanitizer löscht den style, weil er denkt das ist unsicher. So lassen sich XSS-Injections vermeiden. Ich hab das jetzt deaktiviert, weil der MD-Content nicht vom User kommt und wir dann einfach davon ausgehen müssen, dass keine schlimmen Dinge in der Datenbank stehen. Neue Version kommt im laufe des Tages.

**Comment by sheepyhollow** [comment]
Ah, ich dachte mir sowas. Ich frage dennoch mal nach, ob sich ein eigener style lohnt. Es wäre in den DB-Einträgen auf jeden Fall leichter lesbar.

**Comment by mkay-sh** [comment]
Klaro können wir gerne machen. Zeichenvorschläge?

**Comment by sheepyhollow** [comment]
Ich fände etwas mit Strichen zwar "verständlich", aber es sollten wohl eher unwahrscheinliche Zeichen sein. `§...§` könnte man nehmen. Das Symbol taucht bestenfalls im Impressum/Datenschutz auf.

**Comment by mkay-sh** [comment]
Overline ist implementiert.

**Comment by sheepyhollow** [comment]
Wenn das in allen MD-Feldern sicher läuft, kann das auch geschlossen werden.
