### ISSUE TITLE
Suche löschen

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#394]
Bei Eingabe eines Suchbegriffs bzw. von Buchstaben sollte die Lupe zu einem X werden, um die Suche zu löschen/zu verlassen.

**Comment by mkay-sh** [comment]
Der Fokus bleibt aber im Feld falls man wieder was ändern möchte? Oder soll das Feld auch komplett verlassen werden?

**Comment by sheepyhollow** [comment]
Ich plädiere für Fokus verlassen. 
Kann keine UX-Regel dafür nennen, aber wenn ich was anderes suchen will, ändere ich den Text - wenn ich die Suche verlassen will, drücke ich "X".
