### ISSUE TITLE
Galerie Basiskomponente

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#4]
Das Modul stellt eine Thumbnail-Ansicht aller vorhandenen Bilder samt Beschriftung dar.
Bei Auswahl eines Thumbnails wird ein Modal geöffnet, das eine vergrößerte Ansicht des Mineralbildes enthält.
Innerhalb des Modals kann [per Swipe] zwischen den Bildern geblättert werden.
Dieses Modal bildet außerdem die Basis für zukünftige Tools (Zoom, Maßstab, ...)

- [x] Thumbnail Ansicht
- [x] Modal mit vergrößerter Ansicht
- [x] Swipe im Modal zwischen den verschiedenen Bildern
- [x] Automatisch die richtige Bildgröße abhängig vom Bildschirm laden
- [x] `gallery`-Endpoint benutzen
- [x] Swipe auch per Touchgesten
- [x] Funktionsbar am obereren Rand, Link auf Steckbrief
- [x] Sortierfunktion (Default, Alphabetisch) 
- [ ] Kristallsystem Link
- [x] Anzeige in einer Unterseite, statt in einem Modal
- [ ] Zoomfunktion
- [ ] Einblenden einer Skala (mithilfe der World2Pixel Ratio)

**Comment by mkay-sh** [comment]
Bisher gibt es ja nur ein Bild in verschiedenen Größen wenn ich das richtig gesehen habe. Wenn sich das nicht ändert ergibt ein Swipe nicht wirklich viel Sinn. Ist geplant das Backend noch zu erweitern und mehrere Bilder pro Typ zu haben?

**Comment by sheepyhollow** [comment]
> Ist geplant das Backend noch zu erweitern und mehrere Bilder pro Typ zu haben?
Von einigen Handstücken gibt es mehrere Bilder; die tauchen dann aber auch als einzelne Bilder in der Galerie auf (Beispiel _Achat_ mit Vergrößerung oder _Orthoklas_ mit unterschiedlichem Lichteinfall).

Aber wieso sollte ich nicht von Bild zu Bild in Großansicht swipen, ohne jedes Mal wieder auf die Thumbnails zurückzufallen? Oder ist das ein UX-Paradigma?

**Comment by sheepyhollow** [comment]
Bezüglich "vergrößerte" Ansicht im Modal muss man ggf. noch klären, welche Anzeigegröße sinnvoll ist, da dies ja auch eine Frage der Datenmenge sein kann (unabhängig von der Zoomfunktion).
Auf mobilen Geräten ist "bildschirmfüllend" sicher sinnvoll, aber bei hochauflösenden Tablets und Laptops sind das dann auch keine kleinen Bilder mehr.

**Comment by mkay-sh** [comment]
Du hast vollkommen Recht. Natürlich sollte man durch die verschiedenen Einträge gehen können. Ich hatte das gerade irgendwie nur auf ein Bild bezogen und daher nicht den Grund dafür gesehen.

Bezüglich der Datemenge müssen wir nochmal sehen. Habt ihr Definitionen der Auflösungen die sich hinter small, middle, large, etc. verbergen oder sind die nicht einheitlich?

**Comment by sheepyhollow** [comment]
> Habt ihr Definitionen der Auflösungen die sich hinter small, middle, large, etc. verbergen oder sind die nicht einheitlich?

uh... das könnte ich jetzt ausprobieren - oder an @mimischi oder @chgad weiterreichen

**Comment by chgad** [comment]
https://github.com/GeoMatDigital/django-geomat/blob/develop/geomat/stein/models.py#L246

Siehe in der Definition von `image_file`

**Comment by mimischi** [comment]
Die Werte wurden von mir damals arbiträr gewählt. Wir haben die Originaldateien und können die Werte anpassen, sowie weitere Größen hinzufügen. Dafür muss man sich aber über einige Dinge im Klaren sein:

1. Was ist die maximale Breite, die ein Bild einnehmen wird? Sprich, auf mobilen Endgeräten wird es wahrscheinlich `width: 100%` sein, aber wie sieht es auf Desktops aus? Haben wir hier ein zentriertes Modal mit nur `width: 80%`?
2. Für Retina-Displays (moderne macOS Geräte) benötigt man eine höhere Auflösung (2x). Reicht also ein 1024px Bild bei einem normalen Bildschirm, muss für Retina Displays ein 2048px Bild dargestellt werden, damit es nicht verpixelt aussieht.

Mittlerweile unterstützen die Browser auch die automatische Auswahl der richtigen Größe. Man übermittelt einfach alle URLs (mit Angaben zur Größe und benötigten Auflösung), und der Browser entscheidet selbstständig welche Größe runtergeladen wird. Siehe [MDN web docs - Resposive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

Das Problem bei uns ist allerdings, dass es sich um eine SPA handelt und wir optimalerweise auch das nächste Bild im Voraus laden möchten. Ich gehe davon aus, dass es hier einige Implementationen für Angular gibt, welche sich um das Lazy Loading der Bilder, sowie das Laden der richtigen Größe kümmern. Zumindest bin ich über solche Komponenten schon für React und VueJS gestoßen.

**Comment by sheepyhollow** [comment]
Die Galerie sollte den `gallery`-Endpoint nutzen, da die api dort eine Sortierung und Filterung vorgibt.
Aktuell wird der `photographs`-Endpoint genutzt
https://github.com/GeoMatDigital/web-geomat/blob/dev/src/app/modules/gallery/services/photograph.service.ts

**Comment by mkay-sh** [comment]
Alles klar, das kann ich ja ohne Probleme anpassen. Die Ionic Version hat auch den `photographs`-Endpoint benutzt. Da hab ich wohl zu viel abgeschaut.

**Comment by sheepyhollow** [comment]
Ja... das war mir auch nicht so richtig klar :grin:
Also - ich hatte mir die Funktion des gallery-endpoints nicht so recht bewusst gemacht.Aber das ist schon sinnvoll so!

**Comment by mkay-sh** [comment]
Zu klären wäre, ob wir zum Swipen nur einen Button benutzen oder auch Touchgesten unterstützen sollten.

**Comment by sheepyhollow** [comment]
Da man die volle Pracht der Bilder auf einem großen Bildschirm am besten genießen kann, sollte es auf jeden Fall Buttons geben, wobei ich da auch "unsichtbare" ok finde (die nur bei mouseover gezeigt werden oder klickbare Bildbereiche links/rechts/whatever).

ABER ansonsten mobile first oder wie das heißt - also auf jeden Fall intuitive Bedingung auf Mobilgeräten, das heißt Swipe zum Wechseln und ggf. auch Gesten, wenn Zoom implementiert ist.

**Comment by mkay-sh** [comment]
- [ ] Anzeige in einer Unterseite, statt in einem Modal
- [ ] Zoomfunktion
- [ ] Einblenden einer Skala (mithilfe der World2Pixel Ratio)

**Comment by sheepyhollow** [comment]
Thumbnail-Ansicht scrollt nicht (Chrome & FF auf Desktop & Tablet)
