### ISSUE TITLE
Quiz Basiskomponente

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#5]
Das Modul stellt die Fragen als Selbsttests in einer Zufallsreihenfolge dar.
Der bislang einzige Fragetyp sind Auswahlaufgaben; es wird aber nicht zwischen Single- und Multiple-Choice unterschieden (z.B. durch Radiobuttons vs. Checkboxen). Nach Auswahl einer oder mehrerer Antworten muss die Aufgabe über einen Button aktiv abgegeben werden.

Eine Auswertung erfolgt durch Symbole und Farbcodes (Achtung, Barrierefreiheit); zusätzlich wird je gewählter Antwort ein Feedback angezeigt.

Der Modus der Auswertung ist beim derzeitigen Status Quo eine direkte Anzeige nach jeder Frage. Hier sind auch andere Modi vorstellbar.

**Comment by sheepyhollow** [comment]
abhängig von #8 - wartet auf Rückmeldung von den UniQuS-Leuten.

**Comment by mkay-sh** [comment]
Markdown in den Fragen und Antworten unterstützen.

**Comment by sheepyhollow** [comment]
### Quiz-Start
Mit diesen Quizfragen kannst Du Deinen Wissensstand in verschiedenen Teilbereichen überprüfen.
Bei vielen Fragen findest Du im direkten Feedback weitere Informationen, die Dir genauere Hinweise darüber geben, warum Deine Antworten richtig oder falsch waren. So erfährst Du auch zusätzliche Hintergründe und kannst Dein Wissen erweitern.
Du kannst eine Fragenanzahl vorgeben - die Fragen werden zufällig aus dem GeoMat-Fragenpool ausgewählt.
[Auswahlfeld: Fragenanzahl]
[Button: Los geht's!]

**Comment by sheepyhollow** [comment]
#### Quiz-Ende
Du hast n von m Fragen richtig beantwortet!
Als _richtig_ wurde eine Frage nur dann gezählt, wenn alle richtigen Antworten und keine falschen ausgewählt wurden.
[Neue Runde] [Fragenanzahl]

**Comment by sheepyhollow** [comment]
Das sind unsere Vorschläge für Quiz-Start- und Endpage. 

Fragen dazu: 
a) Können wir "Punkte"-abhängiges Feedback geben? Z.B. bei <25%, <50%, <75%, >= 75%, 100%?
b) ist es möglich, sich die beantworteten Fragen zu merken und beim nächsten Lauf rauszufiltern? Session-wise genügt; ggf. auch mit Auswahlbutton.

**Comment by mkay-sh** [comment]
Alles klar.
a ist kein Problem. Gibt mir einfach entsprechende Texte.
b wäre aufwendiger, wenn gewünscht aber umsetzbar.

**Comment by sheepyhollow** [comment]
Da das Quiz jetzt eine Grundfunktionalität hat (Yay! Sehr gut! Texte passen auch so!) können wir dieses hier erstmal schließen und für den weiteren Ausbau eigene Issues verwenden.
