### ISSUE TITLE
Quiz mit UniQuS-Anbindung

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/web-geomat#8]
Das Quiz soll nicht aus der eigenen DB sondern von der externen UniQuS-API befüllt werden.
Hierfür ist das Interface zu klären bzw. die Konformität zum UniQuS-Standard zu überprüfen.
Der interne Standard ist sehr ähnlich, aber es mag Unterschiede geben.

**Comment by mkay-sh** [comment]
Da ich die Quizkomponente jetzt eh neu bauen muss, wäre es ja schön direkt den Standard zu verwenden. Gibt es dazu eine Dokumentation oder hat von euch schon mal jemand geschaut wo die Abweichungen zur aktuellen API sind?

**Comment by sheepyhollow** [comment]
Ich krieg das mal raus.

**Comment by sheepyhollow** [comment]
Also - Zugriff auf UniQuS-Server gibt es aktuell nur über DDP weil hintendran Meteor verwendet wird. Eine REST-API zu bauen sei aber angeblich kein größeres Problem, graphQL im Prinzip auch nicht.
Mockups der Daten habe ich erhalten (schicke ich an @mkay-sh). Da wird sich nicht mehr viel dran ändern.

**Comment by mkay-sh** [comment]
Notwendig wenn wir die Anbindung durchführen. 
#232

**Comment by sheepyhollow** [comment]
Wir machen das mal zu - da passiert ja am Ende doch nichts mehr. 
Sollte noch ein Wunder geschehen, dann können wir das Issue wieder öffnen.
Das Quiz im Backend zu haben ist vllt. auch gut, wenn wir an externe Nutzer denken, die sich ihre eigene App bauen wollen. Die können/wollen ja nicht unbedingt UniQuS nutzen und kriegen trotzdem eine Quiz-App geliefert.
